// <auto-generated />
using System;
using Kalanga.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalanga.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KalangaDbContext))]
    [Migration("20260820124526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.AudioRecordingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cdn_url");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DialectLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dialect_label");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("file_format");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid?>("PhraseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phrase_id");

                    b.Property<string>("SpeakerGender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("speaker_gender");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.HasKey("Id")
                        .HasName("pk_audio_recordings");

                    b.HasIndex("ContributorId")
                        .HasDatabaseName("ix_audio_recordings_contributor_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_audio_recordings_language_id");

                    b.HasIndex("VariationId")
                        .HasDatabaseName("ix_audio_recordings_variation_id");

                    b.HasIndex("PhraseId", "Status")
                        .HasDatabaseName("idx_audio_phrase");

                    b.ToTable("audio_recordings", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ContentPackLessonRecord", b =>
                {
                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("PackId", "LessonId")
                        .HasName("pk_content_pack_lessons");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_content_pack_lessons_lesson_id");

                    b.ToTable("content_pack_lessons", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ContentPackRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<string>("ManifestUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_content_packs");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_content_packs_language_id");

                    b.ToTable("content_packs", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ExerciseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exercise_type");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("PromptData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_data");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_exercises_language_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_exercises_lesson_id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ExerciseResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_exercise_results");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_results_exercise_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_exercise_results_language_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_exercise_results_user_id");

                    b.ToTable("exercise_results", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LanguageVariationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KalangaText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kalanga_text");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phrase_id");

                    b.Property<string>("RegisterLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("register_label");

                    b.HasKey("Id")
                        .HasName("pk_language_variations");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_language_variations_language_id");

                    b.HasIndex("PhraseId")
                        .HasDatabaseName("ix_language_variations_phrase_id");

                    b.ToTable("language_variations", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LearnerGamificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak");

                    b.Property<string>("ProgressLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("progress_level");

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_xp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_learner_gamification");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_learner_gamification_language_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_learner_gamification_user_id");

                    b.ToTable("learner_gamification", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LearnerProgressRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id")
                        .HasName("pk_learner_progress");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_learner_progress_language_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_learner_progress_lesson_id");

                    b.HasIndex("UserId", "LanguageId")
                        .HasDatabaseName("idx_progress_user");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("ix_learner_progress_user_id_lesson_id");

                    b.ToTable("learner_progress", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsScenario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_scenario");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<string>("ReviewFeedback")
                        .HasColumnType("text")
                        .HasColumnName("review_feedback");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ScenarioContext")
                        .HasColumnType("text")
                        .HasColumnName("scenario_context");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("XpReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("ContributorId")
                        .HasDatabaseName("ix_lessons_contributor_id");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_lessons_reviewed_by");

                    b.HasIndex("LanguageId", "Level", "Status")
                        .HasDatabaseName("idx_lessons_language_level");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.PhraseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_translation");

                    b.Property<string>("KalangaText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kalanga_text");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_phrases");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_phrases_language_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("idx_phrases_lesson");

                    b.ToTable("phrases", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_refresh_tokens_language_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RequestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FulfilledByLessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilled_by_lesson_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmitterId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitter_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvote_count");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("FulfilledByLessonId")
                        .HasDatabaseName("ix_requests_fulfilled_by_lesson_id");

                    b.HasIndex("SubmitterId")
                        .HasDatabaseName("ix_requests_submitter_id");

                    b.HasIndex("LanguageId", "UpvoteCount")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_requests_language_upvotes");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RequestUpvoteRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RequestId", "UserId")
                        .HasName("pk_request_upvotes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_request_upvotes_user_id");

                    b.ToTable("request_upvotes", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.SpacedRepetitionRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(2.5m)
                        .HasColumnName("ease_factor");

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("interval_days");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<DateOnly>("NextReviewAt")
                        .HasColumnType("date")
                        .HasColumnName("next_review_at");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phrase_id");

                    b.Property<int>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("repetitions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.HasKey("Id")
                        .HasName("pk_spaced_repetition_records");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_spaced_repetition_records_language_id");

                    b.HasIndex("PhraseId")
                        .HasDatabaseName("ix_spaced_repetition_records_phrase_id");

                    b.HasIndex("VariationId")
                        .HasDatabaseName("ix_spaced_repetition_records_variation_id");

                    b.HasIndex("UserId", "NextReviewAt")
                        .HasDatabaseName("idx_srs_user_next");

                    b.HasIndex("UserId", "PhraseId")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_user_phrase_base")
                        .HasFilter("variation_id IS NULL");

                    b.HasIndex("UserId", "PhraseId", "VariationId")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_user_phrase_variation")
                        .HasFilter("variation_id IS NOT NULL");

                    b.ToTable("spaced_repetition_records", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.SyncCheckpointRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long>("SyncVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("sync_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sync_checkpoints");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_sync_checkpoints_language_id");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique()
                        .HasDatabaseName("idx_sync_user");

                    b.ToTable("sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_users_language_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.AudioRecordingRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audio_recordings_users_contributor_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audio_recordings_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.PhraseRecord", null)
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_audio_recordings_phrases_phrase_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageVariationRecord", null)
                        .WithMany()
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audio_recordings_language_variations_variation_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ContentPackLessonRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_pack_lessons_lessons_lesson_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.ContentPackRecord", null)
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_pack_lessons_content_packs_pack_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ContentPackRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_packs_languages_language_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ExerciseRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_lessons_lesson_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.ExerciseResultRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.ExerciseRecord", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_results_exercises_exercise_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_results_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_results_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LanguageVariationRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_language_variations_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.PhraseRecord", null)
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_variations_phrases_phrase_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LearnerGamificationRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learner_gamification_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_gamification_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LearnerProgressRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learner_progress_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_progress_lessons_lesson_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_progress_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_users_contributor_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lessons_users_reviewed_by");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.PhraseRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phrases_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phrases_lessons_lesson_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RefreshTokenRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RequestRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LessonRecord", null)
                        .WithMany()
                        .HasForeignKey("FulfilledByLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_requests_lessons_fulfilled_by_lesson_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_requests_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_requests_users_submitter_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.RequestUpvoteRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.RequestRecord", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_upvotes_requests_request_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_upvotes_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.SpacedRepetitionRecordRow", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spaced_repetition_records_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.PhraseRecord", null)
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaced_repetition_records_phrases_phrase_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaced_repetition_records_users_user_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageVariationRecord", null)
                        .WithMany()
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_spaced_repetition_records_language_variations_variation_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.SyncCheckpointRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sync_checkpoints_languages_language_id");

                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_checkpoints_users_user_id");
                });

            modelBuilder.Entity("Kalanga.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.HasOne("Kalanga.Infrastructure.Persistence.Entities.LanguageRecord", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_languages_language_id");
                });
#pragma warning restore 612, 618
        }
    }
}
